import { Specialist, ServiceItem, ChildPatient, Branch, Appointment, Lead, HomeworkTask, ScreeningQuestion, PaymentRecord, SpecialistTimeSlot } from '../types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-1',
    nameKg: 'Борбордук Филиал (Дубовый парк)',
    nameRu: 'Центральный Филиал (Дубовый парк)',
    addressKg: 'Чүй проспектиси 114 (Орозбеков көч. кесилиши)',
    addressRu: 'пр. Чуй 114 (пересекает ул. Орозбекова)',
    lat: 42.8765,
    lng: 74.6038,
    phone: '+996 (705) 55-44-33',
    whatsapp: '+996705554433',
    workHoursKg: 'Дүйшөмбү - Ишемби 08:30 - 19:30',
    workHoursRu: 'Понедельник - Суббота 08:30 - 19:30',
    roomsCount: 6,
    specialFeatures: ['Сенсордук чоң зал', 'Логомассаж кабинеттери', 'Томатис терапия', 'Мүмкүнчүлүгү чектелгендерге пандус']
  },
  {
    id: 'branch-2',
    nameKg: 'Түштүк Филиал (Асанбай)',
    nameRu: 'Южный Филиал (Асанбай)',
    addressKg: '12-кичирайон, Аалы Токомбаев көч. 78/2',
    addressRu: '12-мкр, ул. Аалы Токомбаева 78/2',
    lat: 42.8228,
    lng: 74.6285,
    phone: '+996 (550) 22-33-44',
    whatsapp: '+996550223344',
    workHoursKg: 'Дүйшөмбү - Ишемби 08:30 - 19:30',
    workHoursRu: 'Понедельник - Суббота 08:30 - 19:30',
    roomsCount: 5,
    specialFeatures: ['АФК жана кинезио залы', 'АВА класстары', 'Туз шахтасы', 'Ата-энелер күтүү зонасы']
  },
  {
    id: 'branch-3',
    nameKg: 'Батыш Филиал (Азия Молл)',
    nameRu: 'Западный Филиал (Азия Молл)',
    addressKg: 'Чыңгыз Айтматов проспектиси 43',
    addressRu: 'пр. Чынгыза Айтматова 43',
    lat: 42.8550,
    lng: 74.5870,
    phone: '+996 (772) 11-88-99',
    whatsapp: '+996772118899',
    workHoursKg: 'Дүйшөмбү - Ишемби 08:30 - 19:30',
    workHoursRu: 'Понедельник - Суббота 08:30 - 19:30',
    roomsCount: 4,
    specialFeatures: ['Эрте куракты диагностикалоо', 'Сенсордук интеграция', 'Интерактивдүү логопеддик кум']
  }
];

export const INITIAL_SPECIALISTS: Specialist[] = [
  {
    id: 'spec-1',
    name: 'Наргиза Токтосунова',
    role: 'логопед-дефектолог',
    titleKg: 'Башкы логопед-дефектолог, логомассажист',
    titleRu: 'Главный логопед-дефектолог, специалист по логомассажу',
    experienceYears: 14,
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    bioKg: 'КР Улуттук Университетинин дефектология бөлүмүн артыкчылык менен бүтүргөн. Москва институтунда зонддук массаж жана оор кеп бузулуулары (алалия, дизартрия) боюнча адистешкен.',
    bioRu: 'Окончила дефектологический факультет с отличием. Специализация в Институте коррекционной педагогики (Москва) по зондовому массажу и тяжелым речевым нарушениям.',
    phone: '+996 705 554433',
    rating: 4.98,
    roomNumber: 'Кабинет №1 (Логопедия)',
    hourlyRate: 900,
    activePatientsCount: 18,
    specializationTags: ['Дизартрия', 'Алалия', 'Логомассаж', 'Тыбыштарды коюу', 'ЗПРР']
  },
  {
    id: 'spec-2',
    name: 'Азамат Асанов',
    role: 'сенсордук_терапевт',
    titleKg: 'Сенсордук интеграция жана АФК реабилитологу',
    titleRu: 'Специалист по сенсорной интеграции и реабилитолог АФК',
    experienceYears: 10,
    photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    bioKg: 'Эл аралык Ayres Sensory Integration (ASI) тастыктамасынын ээси. ДЦП, диспраксия жана вестибулярдык сезгичтикти жөнгө салуу боюнча 600дөн ашык балага жардам берген.',
    bioRu: 'Сертифицированный специалист по сенсорной интеграции Джин Айрес. Опыт реабилитации детей с ДЦП, диспраксией и нарушениями моторного планирования.',
    phone: '+996 550 223344',
    rating: 4.95,
    roomNumber: 'Сенсордук чоң зал (№3)',
    hourlyRate: 1000,
    activePatientsCount: 15,
    specializationTags: ['Сенсорная интеграция', 'ДЦП реабилитация', 'Баланс & Моторика', 'АФК']
  },
  {
    id: 'spec-3',
    name: 'Айсулуу Исакова',
    role: 'ава_терапевт',
    titleKg: 'Сертификатталган АВА-терапевт (RBT / ИБА)',
    titleRu: 'Сертифицированный АВА-терапевт (RBT / IBA)',
    experienceYears: 8,
    photoUrl: 'https://images.unsplash.com/photo-1594824813589-4a9463c68fb7?auto=format&fit=crop&w=600&q=80',
    bioKg: 'Аутизм спектриндеги (РАС) балдардын жүрүм-турумун прикладдык талдоо боюнча адис. PECS карточкалары, визуалдык колдоо жана социалдаштыруу программаларын түзөт.',
    bioRu: 'Специалист по прикладному анализу поведения (ABA). Внедрение альтернативной коммуникации PECS, коррекция нежелательного поведения, навыки самообслуживания.',
    phone: '+996 772 118899',
    rating: 4.97,
    roomNumber: 'АВА класс (№4)',
    hourlyRate: 1100,
    activePatientsCount: 14,
    specializationTags: ['РАС / Аутизм', 'PECS коммуникация', 'Жүрүм-турум коррекциясы', 'Имитация']
  },
  {
    id: 'spec-4',
    name: 'Чолпон Бекболотова',
    role: 'дефектолог',
    titleKg: 'Нейродефектолог, таанып-билүү процесстерин өнүктүрүү адиси',
    titleRu: 'Нейродефектолог, специалист когнитивного развития',
    experienceYears: 9,
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    bioKg: 'ЗПР, СДВГ жана мектепке даярдоодо кыйынчылык көргөн балдарга арналган жеке программалардын автору. Нейроигралар жана ойлонууну өнүктүрүүчү көнүгүүлөр.',
    bioRu: 'Автор индивидуальных методик для детей с ЗПР, СДВГ. Развитие высших психических функций: память, внимание, логика, пространственное мышление.',
    phone: '+996 700 998877',
    rating: 4.92,
    roomNumber: 'Кабинет №2 (Дефектология)',
    hourlyRate: 900,
    activePatientsCount: 16,
    specializationTags: ['ЗПР / ЗПРР', 'Нейроигры', 'СДВГ', 'Логика & Ойлонуу', 'Мектепке даярдоо']
  },
  {
    id: 'spec-5',
    name: 'Руслан Жумабеков',
    role: 'афк_инструктор',
    titleKg: 'Адаптивдүү дене тарбия жана кинезиотерапия инструктору',
    titleRu: 'Инструктор АФК и кинезиотерапии для детей',
    experienceYears: 7,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    bioKg: 'Кыргыз дене тарбия академиясынын реабилитация бөлүмү. ДЦП менен жабыркаган балдардын булчуңдарын созуу, муундардын кыймылдуулугун жогорулатуу жана басууну үйрөтүү.',
    bioRu: 'Специалист по лечебной физкультуре и моторной коррекции. Растяжка, работа с гипертонусом и гипотонусом, постановка паттерна ходьбы.',
    phone: '+996 555 334455',
    rating: 4.89,
    roomNumber: 'АФК залы (№5)',
    hourlyRate: 900,
    activePatientsCount: 12,
    specializationTags: ['ДЦП реабилитация', 'Басуу көндүмү', 'АФК тренажерлор', 'Спастиканы басуу']
  }
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    nameKg: 'Комплекстүү логопедиялык-дефектологиялык диагностика',
    nameRu: 'Комплексная логопедическая и дефектологическая диагностика',
    category: 'диагностика',
    price: 1200,
    durationMinutes: 50,
    descriptionKg: 'Баланын сүйлөө аппараты, тыбыштарды айтуусу, фонематикалык угуусу, сөз байлыгы, эске тутуусу жана эмоционалдык-эрктик чөйрөсүн толук текшерүү + адистин корутундусу.',
    descriptionRu: 'Полное обследование речевого аппарата, звукопроизношения, фонематического слуха, словарного запаса, высших психических функций + письменное заключение.',
    targetConditions: ['Бардык балдарга', 'Сүйлөбөгөн балдар', 'ЗПРР', 'РАС'],
    icon: 'Stethoscope',
    isPopular: true
  },
  {
    id: 'srv-2',
    nameKg: 'Жеке логопедиялык сабак жана тыбыштарды коюу',
    nameRu: 'Индивидуальное логопедическое занятие и постановка звуков',
    category: 'логопедия',
    price: 900,
    durationMinutes: 40,
    descriptionKg: 'Тыбыштарды коюу (Р, Л, Ш, Ж, С ж.б.), автоматизациялоо, артикуляциялык гимнастика, сүйлөм түзүү жана байланыштуу кепти өстүрүү.',
    descriptionRu: 'Постановка звуков (Р, Л, Шипящие, Свистящие), автоматизация, артикуляционная гимнастика, развитие связной речи и слоговой структуры.',
    targetConditions: ['Дислалия', 'Дизартрия', 'ЗПРР', 'Тил мүчүлүштүктөрү'],
    icon: 'Mic',
    isPopular: true
  },
  {
    id: 'srv-3',
    nameKg: 'Логопедиялык зонддук жана кол массажы',
    nameRu: 'Логопедический зондовый и ручной массаж',
    category: 'логопедия',
    price: 1000,
    durationMinutes: 30,
    descriptionKg: 'Тилдин, жаактын, эриндин булчуң тонусун нормалдаштыруу. Дизартрия, мотордук алалия жана шилекей агуусунда өтө эффективдүү.',
    descriptionRu: 'Нормализация мышечного тонуса языка, губ, щек и мягкого неба. Показан при дизартрии, гиперсаливации, спастичности.',
    targetConditions: ['Дизартрия', 'Мотордук алалия', 'ДЦП', 'Гипертонус'],
    icon: 'Sparkles'
  },
  {
    id: 'srv-4',
    nameKg: 'Дефектолог менен жеке өнүктүрүү сабагы',
    nameRu: 'Индивидуальное занятие с дефектологом',
    category: 'дефектолог',
    price: 900,
    durationMinutes: 45,
    descriptionKg: 'Көңүл буруу, эске тутуу, логикалык ой жүгүртүү, мейкиндикте багыт алуу, майда моторика жана курчап турган дүйнөнү таанып-билүү.',
    descriptionRu: 'Развитие высших психических функций: концентрация внимания, память, логика, мелкая моторика, пространственная ориентация.',
    targetConditions: ['ЗПР', 'ЗПРР', 'СДВГ', 'Таанып-билүү артта калуусу'],
    icon: 'Brain'
  },
  {
    id: 'srv-5',
    nameKg: 'Сенсордук интеграция (Атайын жабдылган залда)',
    nameRu: 'Сенсорная интеграция (В специализированном зале)',
    category: 'сенсорика',
    price: 1000,
    durationMinutes: 45,
    descriptionKg: 'Вестибулярдык, тактильдик жана проприоцептивдик системаларды жөнгө салуу (сенсордук качели, сухой бассейн, гравитациялык шаты, батут).',
    descriptionRu: 'Гармонизация сенсорных систем: вестибулярная, тактильная, проприоцептивная стимуляция на специальном оборудовании.',
    targetConditions: ['РАС / Аутизм', 'Сенсордук сезгичтик', 'СДВГ', 'Диспраксия'],
    icon: 'Activity',
    isPopular: true
  },
  {
    id: 'srv-6',
    nameKg: 'АВА терапия (Жүрүм-турумду прикладдык анализдөө)',
    nameRu: 'АВА терапия (Прикладной анализ поведения)',
    category: 'ава',
    price: 1100,
    durationMinutes: 50,
    descriptionKg: 'Аутизм жана жүрүм-турумдук кыйынчылыктары бар балдар үчүн жеке сессия. PECS альтернативдик коммуникация, имитация, социалдашуу.',
    descriptionRu: 'Коррекция поведения, развитие коммуникации PECS, формирование учебного поведения, самостоятельность и социализация.',
    targetConditions: ['РАС / Аутизм', 'Агрессия/Тантрум', 'Коммуникация жоктугу'],
    icon: 'HeartHandshake',
    isPopular: true
  },
  {
    id: 'srv-7',
    nameKg: 'АФК жана ДЦП реабилитациясы',
    nameRu: 'АФК и двигательная реабилитация при ДЦП',
    category: 'афк',
    price: 900,
    durationMinutes: 45,
    descriptionKg: 'Адаптивдүү дене тарбия, кыймыл-аракетти жакшыртуу, спастиканы басуу, туура басууну жана тең салмактуулукту калыптандыруу.',
    descriptionRu: 'Лечебная физкультура, улучшение подвижности суставов, снижение спастики, тренировка баланса и координации.',
    targetConditions: ['ДЦП', 'Гипотонус / Гипертонус', 'Мотордук артта калуу'],
    icon: 'Footprints'
  },
  {
    id: 'srv-8',
    nameKg: 'Абонемент: 12 сабак (Логопедия / Дефектология)',
    nameRu: 'Абонемент: 12 занятий (Логопедия / Дефектология)',
    category: 'комплекс',
    price: 9600,
    durationMinutes: 45,
    descriptionKg: '1 айлык системалуу курс (1 сабагы 800 сомдон эсептелет). Үй тапшырмалары жана жумалык мониторинг камтылган.',
    descriptionRu: 'Месячный систематический курс (800 сом за занятие). Включает домашние задания и динамический мониторинг.',
    targetConditions: ['Туруктуу натыйжа үчүн', '1-айлык курс'],
    icon: 'CalendarCheck',
    isPopular: true
  },
  {
    id: 'srv-9',
    nameKg: 'Абонемент: 12 сабак (Сенсорика / АВА-терапия)',
    nameRu: 'Абонемент: 12 занятий (Сенсорика / АВА-терапия)',
    category: 'комплекс',
    price: 11400,
    durationMinutes: 50,
    descriptionKg: 'Сенсордук интеграция же АВА терапиясы боюнча 12 жеке сабак. Жеке протокол жана видео-отчеттор.',
    descriptionRu: '12 индивидуальных занятий по сенсорной интеграции или АВА. Включает индивидуальный протокол и видеоотчетность.',
    targetConditions: ['РАС', 'Аутизм', 'Сенсордук дисфункция'],
    icon: 'Layers'
  },
  {
    id: 'srv-10',
    nameKg: 'Комплекстүү Интенсив «Логос+ Өнүгүү» (24 сабак)',
    nameRu: 'Комплексный Интенсив «Логос+ Развитие» (24 занятия)',
    category: 'комплекс',
    price: 21600,
    durationMinutes: 50,
    descriptionKg: 'Эң натыйжалуу интенсив: Логопед (8x) + Сенсордук зал (8x) + АВА же АФК (8x) + Башкы адистин көзөмөлү.',
    descriptionRu: 'Максимально эффективный интенсив: Логопед (8x) + Сенсорный зал (8x) + АВА или АФК (8x) + кураторство ведущего эксперта.',
    targetConditions: ['РАС', 'ДЦП', 'ЗПРР', 'Оор кеп бузулуулары'],
    icon: 'Award',
    isPopular: true
  }
];

export const INITIAL_PATIENTS: ChildPatient[] = [
  {
    id: 'p-1',
    cardCode: 'LOGOS-101',
    accessPin: '1234',
    name: 'Амир Эмилбеков',
    birthDate: '2022-04-12',
    age: 4,
    gender: 'male',
    diagnosis: 'РАС / Аутизм спектри',
    parentName: 'Айзада Эмилбекова',
    phone: '+996 702 445566',
    email: 'aizada.e@gmail.com',
    branchId: 'branch-1',
    assignedSpecialistId: 'spec-3',
    assignedSpecialistName: 'Айсулуу Исакова',
    remainingLessons: 8,
    totalSessionsCompleted: 16,
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=300&q=80',
    speechScore: 35,
    sensoryScore: 48,
    motorScore: 65,
    socialScore: 40,
    notes: 'Көзгө кароо контакты жакшырып жатат. PECS 2-этабына өттүк. Үн чыгарууга кызыгуусу пайда болду.',
    allergiesOrPrecautions: 'Катуу үн жана жаркыраган жарыктан чочуйт, наушник керек',
    createdAt: '2026-06-10',
    iomPlan: {
      goals: ['Көз байланышын 5+ секундага чейин жеткирүү', 'PECS карточкасы аркылуу суу/оюнчук суроо', 'Сенсордук жүктөмдү азайтуу'],
      recommendedProgram: 'АВА-терапия + Сенсордук интеграция (Жумасына 4 жолу)',
      frequency: 'Дш, Шш, Бш, Жм (10:00)',
      assignedSpecialists: ['Айсулуу Исакова (АВА)', 'Азамат Асанов (Сенсорика)'],
      milestones: [
        { stage: '1-ай (Адаптация)', focus: 'Терапевт менен байланыш жана качуу жүрүм-турумун азайтуу', status: 'completed' },
        { stage: '2-ай (Коммуникация)', focus: 'PECS 1-2 фазалары, имитациялык кыймылдар', status: 'in-progress' },
        { stage: '3-ай (Сүйлөө)', focus: 'Жөнөкөй үндөрдү жана сөздөрдү тууроо', status: 'pending' }
      ],
      homeRecommendations: [
        'Үйдө суроолорго дароо жооп бербей, PECS карточкасын сунуусун күтүү',
        'Күн сайын 15 мүнөт сенсордук куту (буурчак/күрүч) менен ойноо'
      ],
      lastUpdated: '2026-08-20'
    }
  },
  {
    id: 'p-2',
    cardCode: 'LOGOS-102',
    accessPin: '1234',
    name: 'Нурсултан Касымов',
    birthDate: '2021-08-15',
    age: 5,
    gender: 'male',
    diagnosis: 'ЗПР / ЗПРР (Кечигүү)',
    parentName: 'Гүлмира Касымова',
    phone: '+996 555 778899',
    email: 'gulmira.k@mail.ru',
    branchId: 'branch-1',
    assignedSpecialistId: 'spec-1',
    assignedSpecialistName: 'Наргиза Токтосунова',
    remainingLessons: 5,
    totalSessionsCompleted: 22,
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=300&q=80',
    speechScore: 68,
    sensoryScore: 75,
    motorScore: 80,
    socialScore: 70,
    notes: '«Р» жана «Ш» тыбыштары коюлду. Азыр сүйлөм ичинде туура айтуу (автоматизация) жүрүп жатат.',
    allergiesOrPrecautions: 'Цитруска аллергиясы бар',
    createdAt: '2026-05-02',
    iomPlan: {
      goals: ['«Р» тыбышын таза айтуу', '3-4 сөздөн турган байланыштуу сүйлөм түзүү', 'Фонематикалык угууну курчутуу'],
      recommendedProgram: 'Логопедия + Логомассаж + Дефектолог',
      frequency: 'Жумасына 3 жолу (Дш, Шр, Жм 14:00)',
      assignedSpecialists: ['Наргиза Токтосунова (Логопед)', 'Чолпон Бекболотова (Дефектолог)'],
      milestones: [
        { stage: '1-ай', focus: 'Тилдин булчуң тонусун логомассаж менен бошотуу', status: 'completed' },
        { stage: '2-ай', focus: '«Р», «Ш», «Ж» тыбыштарын артикуляциялык зонд менен коюу', status: 'completed' },
        { stage: '3-ай', focus: 'Сөздөрдө жана ырларда тыбышты колдонуу', status: 'in-progress' }
      ],
      homeRecommendations: [
        '«Атчандар» жана «Козу карын» артикуляциялык гимнастикасы (күнүнө 2 жолу 5 мин)',
        'Үн чыгарып жомок окуп берүү жана суроо берүү'
      ],
      lastUpdated: '2026-08-25'
    }
  },
  {
    id: 'p-3',
    cardCode: 'LOGOS-103',
    accessPin: '1234',
    name: 'Арууке Бакытова',
    birthDate: '2020-11-20',
    age: 6,
    gender: 'female',
    diagnosis: 'ДЦП (Церебралдык шал)',
    parentName: 'Бакыт Садиров',
    phone: '+996 770 123456',
    email: 'bakyt.sadirov@gmail.com',
    branchId: 'branch-2',
    assignedSpecialistId: 'spec-5',
    assignedSpecialistName: 'Руслан Жумабеков',
    remainingLessons: 10,
    totalSessionsCompleted: 34,
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=300&q=80',
    speechScore: 55,
    sensoryScore: 60,
    motorScore: 45,
    socialScore: 65,
    notes: 'Оң буттун спастикасы бир кыйла азайды. Балансирде 15 секунд өз алдынча тура алды. Логомассаж уланууда.',
    allergiesOrPrecautions: 'Жыгылып кетүү коркунучу бар, колдоо керек',
    createdAt: '2026-03-15',
    iomPlan: {
      goals: ['Тең салмактуулукту кармоо жана басуу аракетин жеңилдетүү', 'Дизартрияны азайтып, үндү так чыгаруу'],
      recommendedProgram: 'АФК + Кинезио + Логомассаж',
      frequency: 'Жумасына 3 жолу',
      assignedSpecialists: ['Руслан Жумабеков (АФК)', 'Наргиза Токтосунова (Логопед)'],
      milestones: [
        { stage: '1-ай', focus: 'Булчуңдарды созуу (растяжка) жана контрактуранын алдын алуу', status: 'completed' },
        { stage: '2-ай', focus: 'Швеция шатысы жана баланс аянтчасында көнүгүүлөр', status: 'in-progress' },
        { stage: '3-ай', focus: 'Өз алдынча тепкичке чыгуу көндүмү', status: 'pending' }
      ],
      homeRecommendations: [
        'Эртең мененки бут булчуңдарын укалоо',
        'Жумшак топ менен буттун манжаларын кысуу'
      ],
      lastUpdated: '2026-08-22'
    }
  },
  {
    id: 'p-4',
    name: 'Даниэль Югай',
    birthDate: '2023-01-10',
    age: 3,
    gender: 'male',
    diagnosis: 'Мотордук / Сенсордук алалия',
    parentName: 'Елена Югай',
    phone: '+996 708 909090',
    branchId: 'branch-1',
    assignedSpecialistId: 'spec-1',
    assignedSpecialistName: 'Наргиза Токтосунова',
    remainingLessons: 12,
    totalSessionsCompleted: 4,
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1595454223600-91fbdd77e58e?auto=format&fit=crop&w=300&q=80',
    speechScore: 20,
    sensoryScore: 50,
    motorScore: 70,
    socialScore: 50,
    notes: 'Сүйлөө деми начар. Артикуляциялык аппаратты даярдап жатабыз.',
    createdAt: '2026-08-10'
  },
  {
    id: 'p-5',
    name: 'Айбийке Маратова',
    birthDate: '2021-02-28',
    age: 5,
    gender: 'female',
    diagnosis: 'СДВГ / Гиперактивдүүлүк',
    parentName: 'Марат Орозов',
    phone: '+996 559 881122',
    branchId: 'branch-3',
    assignedSpecialistId: 'spec-4',
    assignedSpecialistName: 'Чолпон Бекболотова',
    remainingLessons: 0,
    totalSessionsCompleted: 24,
    status: 'diagnostic',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=300&q=80',
    speechScore: 85,
    sensoryScore: 60,
    motorScore: 88,
    socialScore: 60,
    notes: 'Көңүл буруусу 15 мүнөткө чейин узарды. Жаңы абонементке муктаж.',
    createdAt: '2026-04-18'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    childId: 'p-1',
    childName: 'Амир Эмилбеков',
    childAge: 4,
    parentName: 'Айзада Эмилбекова',
    phone: '+996 702 445566',
    serviceId: 'srv-6',
    serviceName: 'АВА терапия (Жүрүм-турумду прикладдык анализдөө)',
    specialistId: 'spec-3',
    specialistName: 'Айсулуу Исакова',
    room: 'АВА класс (№4)',
    branchId: 'branch-1',
    date: '2026-08-27',
    time: '09:00',
    status: 'completed',
    paymentStatus: 'subscription',
    price: 1100,
    notes: 'PECS карточкалары менен ийгиликтүү иштеди.',
    createdAt: '2026-08-26'
  },
  {
    id: 'apt-2',
    childId: 'p-2',
    childName: 'Нурсултан Касымов',
    childAge: 5,
    parentName: 'Гүлмира Касымова',
    phone: '+996 555 778899',
    serviceId: 'srv-2',
    serviceName: 'Жеке логопедиялык сабак жана тыбыштарды коюу',
    specialistId: 'spec-1',
    specialistName: 'Наргиза Токтосунова',
    room: 'Кабинет №1 (Логопедия)',
    branchId: 'branch-1',
    date: '2026-08-27',
    time: '10:00',
    status: 'scheduled',
    paymentStatus: 'subscription',
    price: 900,
    notes: '«Р» тыбышын ырда колдонуу.',
    createdAt: '2026-08-26'
  },
  {
    id: 'apt-3',
    childId: 'p-3',
    childName: 'Арууке Бакытова',
    childAge: 6,
    parentName: 'Бакыт Садиров',
    phone: '+996 770 123456',
    serviceId: 'srv-7',
    serviceName: 'АФК жана ДЦП реабилитациясы',
    specialistId: 'spec-5',
    specialistName: 'Руслан Жумабеков',
    room: 'АФК залы (№5)',
    branchId: 'branch-2',
    date: '2026-08-27',
    time: '11:00',
    status: 'scheduled',
    paymentStatus: 'subscription',
    price: 900,
    notes: 'Баланс тренажеру.',
    createdAt: '2026-08-26'
  },
  {
    id: 'apt-4',
    childName: 'Султан Маратов (Жаңы)',
    childAge: 3,
    parentName: 'Динара Маратова',
    phone: '+996 709 112233',
    serviceId: 'srv-1',
    serviceName: 'Комплекстүү логопедиялык-дефектологиялык диагностика',
    specialistId: 'spec-1',
    specialistName: 'Наргиза Токтосунова',
    room: 'Кабинет №1 (Логопедия)',
    branchId: 'branch-1',
    date: '2026-08-27',
    time: '14:00',
    status: 'scheduled',
    paymentStatus: 'paid',
    price: 1200,
    notes: 'Алгачкы текшерүү: сүйлөөсү кечиккен.',
    createdAt: '2026-08-26'
  },
  {
    id: 'apt-5',
    childId: 'p-1',
    childName: 'Амир Эмилбеков',
    childAge: 4,
    parentName: 'Айзада Эмилбекова',
    phone: '+996 702 445566',
    serviceId: 'srv-5',
    serviceName: 'Сенсордук интеграция',
    specialistId: 'spec-2',
    specialistName: 'Азамат Асанов',
    room: 'Сенсордук чоң зал (№3)',
    branchId: 'branch-1',
    date: '2026-08-27',
    time: '15:30',
    status: 'scheduled',
    paymentStatus: 'subscription',
    price: 1000,
    notes: 'Качели жана проприоцепция.',
    createdAt: '2026-08-26'
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    parentName: 'Каныкей Ибраева',
    phone: '+996 700 332211',
    childName: 'Тимур',
    childAge: 3,
    concernKg: '3 жашка чыкты, сүйлөбөйт, колу менен гана көрсөтөт. Көзгө аз карайт.',
    concernRu: '3 года, не говорит, только указывает пальцем. Слабый зрительный контакт.',
    source: 'chatbot',
    status: 'new',
    preferredBranch: 'branch-1',
    createdAt: '2026-08-27 08:12'
  },
  {
    id: 'lead-2',
    parentName: 'Алмаз Жумабеков',
    phone: '+996 555 129988',
    childName: 'Элина',
    childAge: 5,
    concernKg: '«Р» жана «Л» тыбыштарын айта албайт, мектепке чейин оңдогубуз келет.',
    concernRu: 'Не выговаривает «Р» и «Л», хотим исправить до школы.',
    source: 'screener',
    status: 'contacted',
    preferredBranch: 'branch-2',
    createdAt: '2026-08-26 18:40'
  },
  {
    id: 'lead-3',
    parentName: 'Мадина Садыкова',
    phone: '+996 771 908070',
    childName: 'Ильяс',
    childAge: 4,
    concernKg: 'ДЦП гемипарез, оң буту начар, сенсордук зал жана АФК керек.',
    concernRu: 'ДЦП гемипарез, слабая правая нога, нужен сенсорный зал и АФК.',
    source: 'website_form',
    status: 'diagnosed',
    preferredBranch: 'branch-2',
    createdAt: '2026-08-25 15:20'
  }
];

export const INITIAL_HOMEWORK: HomeworkTask[] = [
  {
    id: 'hw-1',
    childId: 'p-1',
    titleKg: 'Сенсордук оюн: Күрүч кутусундагы оюнчуктар',
    titleRu: 'Сенсорная игра: Поиск игрушек в рисовой коробке',
    instructionsKg: 'Чоң идишке күрүч салып, ичине бала жакшы көргөн 3 чакан оюнчукту жашырыңыз. Бала колу менен сыйпалап таап чыгып, PECS карточкасы менен атасын.',
    instructionsRu: 'В коробку с рисом спрячьте 3 мелкие игрушки. Ребенок на ощупь находит их и просит карточкой PECS.',
    category: 'sensory',
    durationMinutes: 15,
    isCompleted: false,
    assignedDate: '2026-08-27',
    icon: 'Package'
  },
  {
    id: 'hw-2',
    childId: 'p-2',
    titleKg: 'Артикуляциялык көнүгүү: «Атчандар» жана «Мотор»',
    titleRu: 'Артикуляционная гимнастика: «Лошадка» и «Моторчик»',
    instructionsKg: 'Күзгү алдында тилдин учун таңдайга чапкылап «цок-цок» үнүн чыгаруу (20 жолу). Андан соң терең дем алып «Д-д-д-р-р-р» деп моторду жүргүзүү.',
    instructionsRu: 'Перед зеркалом цокать язычком (20 раз). Затем на выдохе произносить «Д-д-д-р-р-р» заводя моторчик.',
    category: 'articular',
    durationMinutes: 10,
    isCompleted: true,
    assignedDate: '2026-08-26',
    completedAt: '2026-08-26 19:30',
    icon: 'Smile'
  },
  {
    id: 'hw-3',
    childId: 'p-3',
    titleKg: 'АФК көнүгүүсү: Топту буттун манжалары менен кармоо',
    titleRu: 'АФК упражнение: Захват массажного мячика пальцами стопы',
    instructionsKg: 'Отургучка отуруп, тикенек массаж тобун же жоолукту буттун манжалары менен кармап көтөрүү (ар бир бутка 10 жолу).',
    instructionsRu: 'Сидя на стуле, захватывать игольчатый мячик или платочек пальчиками стоп (по 10 раз на каждую ногу).',
    category: 'motor',
    durationMinutes: 12,
    isCompleted: false,
    assignedDate: '2026-08-27',
    icon: 'Footprints'
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    childName: 'Амир Эмилбеков',
    parentName: 'Айзада Эмилбекова',
    phone: '+996 702 445566',
    amount: 11000,
    paymentMethod: 'mbank',
    serviceType: 'subscription_12',
    serviceName: 'АВА терапия (12 сабак абонемент)',
    receiptNumber: 'CHK-2026-0819',
    date: '2026-08-27',
    time: '09:15',
    status: 'paid',
    notes: 'MBank QR аркылуу төлөндү'
  },
  {
    id: 'pay-2',
    childName: 'Нурсултан Касымов',
    parentName: 'Гүлмира Касымова',
    phone: '+996 555 778899',
    amount: 9000,
    paymentMethod: 'odengi',
    serviceType: 'subscription_12',
    serviceName: 'Жеке логопедия (12 сабак)',
    receiptNumber: 'CHK-2026-0820',
    date: '2026-08-27',
    time: '10:05',
    status: 'paid',
    notes: 'О!Деньги капчык'
  },
  {
    id: 'pay-3',
    childName: 'Султан Маратов',
    parentName: 'Динара Маратова',
    phone: '+996 709 112233',
    amount: 1200,
    paymentMethod: 'cash',
    serviceType: 'diagnostic',
    serviceName: 'Комплекстүү диагностика',
    receiptNumber: 'CHK-2026-0821',
    date: '2026-08-27',
    time: '14:10',
    status: 'paid',
    notes: 'Накталай кассага'
  },
  {
    id: 'pay-4',
    childName: 'Арууке Бакытова',
    parentName: 'Бакыт Садиров',
    phone: '+996 770 123456',
    amount: 9000,
    paymentMethod: 'elkart',
    serviceType: 'subscription_12',
    serviceName: 'АФК жана ДЦП реабилитациясы (12 сабак)',
    receiptNumber: 'CHK-2026-0822',
    date: '2026-08-26',
    time: '11:40',
    status: 'paid',
    notes: 'Элкарт POS терминал'
  },
  {
    id: 'pay-5',
    childName: 'Даниэль Югай',
    parentName: 'Елена Югай',
    phone: '+996 708 909090',
    amount: 10000,
    paymentMethod: 'visa',
    serviceType: 'subscription_12',
    serviceName: 'Сенсордук интеграция (12 сабак)',
    receiptNumber: 'CHK-2026-0823',
    date: '2026-08-25',
    time: '16:00',
    status: 'paid',
    notes: 'Visa / Optima Bank'
  }
];

export const INITIAL_TIME_SLOTS: SpecialistTimeSlot[] = [
  { id: 'ts-1', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '09:00', isBooked: true, status: 'booked', childName: 'Адилет С.', serviceName: 'Логопедия', room: 'Кабинет №1' },
  { id: 'ts-2', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '10:00', isBooked: true, status: 'booked', childName: 'Нурсултан К.', serviceName: 'Логопедия', room: 'Кабинет №1' },
  { id: 'ts-3', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '11:00', isBooked: false, status: 'available', room: 'Кабинет №1' },
  { id: 'ts-4', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '12:00', isBooked: false, status: 'break', notes: 'Түшкү тыныгуу' },
  { id: 'ts-5', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '14:00', isBooked: true, status: 'booked', childName: 'Султан М.', serviceName: 'Диагностика', room: 'Кабинет №1' },
  { id: 'ts-6', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '15:00', isBooked: false, status: 'available', room: 'Кабинет №1' },
  { id: 'ts-7', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '16:00', isBooked: false, status: 'available', room: 'Кабинет №1' },
  { id: 'ts-8', specialistId: 'spec-1', specialistName: 'Наргиза Токтосунова', date: '2026-08-27', time: '17:00', isBooked: false, status: 'available', room: 'Кабинет №1' },

  { id: 'ts-9', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '09:00', isBooked: false, status: 'available', room: 'Сенсордук зал' },
  { id: 'ts-10', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '10:00', isBooked: false, status: 'available', room: 'Сенсордук зал' },
  { id: 'ts-11', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '11:00', isBooked: true, status: 'booked', childName: 'Эмир Ж.', serviceName: 'Сенсорика', room: 'Сенсордук зал' },
  { id: 'ts-12', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '12:00', isBooked: false, status: 'break', notes: 'Тыныгуу' },
  { id: 'ts-13', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '14:00', isBooked: false, status: 'available', room: 'Сенсордук зал' },
  { id: 'ts-14', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '15:30', isBooked: true, status: 'booked', childName: 'Амир Э.', serviceName: 'Сенсорика', room: 'Сенсордук зал' },
  { id: 'ts-15', specialistId: 'spec-2', specialistName: 'Азамат Асанов', date: '2026-08-27', time: '17:00', isBooked: false, status: 'available', room: 'Сенсордук зал' },

  { id: 'ts-16', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '09:00', isBooked: true, status: 'booked', childName: 'Амир Э.', serviceName: 'АВА терапия', room: 'АВА класс' },
  { id: 'ts-17', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '10:30', isBooked: false, status: 'available', room: 'АВА класс' },
  { id: 'ts-18', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '12:00', isBooked: false, status: 'break', notes: 'Тыныгуу' },
  { id: 'ts-19', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '14:00', isBooked: true, status: 'booked', childName: 'Тимур И.', serviceName: 'АВА терапия', room: 'АВА класс' },
  { id: 'ts-20', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '15:30', isBooked: false, status: 'available', room: 'АВА класс' },
  { id: 'ts-21', specialistId: 'spec-3', specialistName: 'Айсулуу Исакова', date: '2026-08-27', time: '17:00', isBooked: false, status: 'available', room: 'АВА класс' }
];

export const SCREENING_QUESTIONS: ScreeningQuestion[] = [
  {
    id: 1,
    questionKg: 'Балаңыз атын айтып чакырганда сизге карап жооп береби?',
    questionRu: 'Откликается ли ваш ребенок на свое имя, когда вы его зовете?',
    category: 'autism_mchat',
    ageRange: '1.5 - 7 жаш',
    options: [
      { labelKg: 'Ооба, дайыма дароо карайт', labelRu: 'Да, всегда сразу смотрит', points: 0, riskWeight: 0 },
      { labelKg: 'Кээде гана, же бир нече жолу кайталаганда', labelRu: 'Редко или после нескольких повторов', points: 1, riskWeight: 1 },
      { labelKg: 'Такыр карабайт, кулагы укпагандай сезилет', labelRu: 'Почти не откликается, как будто не слышит', points: 2, riskWeight: 2 }
    ]
  },
  {
    id: 2,
    questionKg: 'Балаңыз бир нерсеге кызыкканда сөөмөйү (указательный жест) менен көрсөтөбү?',
    questionRu: 'Использует ли ребенок указательный палец, чтобы показать на интересный предмет?',
    category: 'autism_mchat',
    ageRange: '1.5 - 5 жаш',
    options: [
      { labelKg: 'Ооба, каалаган нерсесин колу менен так көрсөтөт', labelRu: 'Да, активно показывает пальчиком', points: 0, riskWeight: 0 },
      { labelKg: 'Жок, чоң адамдын колун жетелеп алып барып коёт', labelRu: 'Нет, берет руку взрослого как инструмент', points: 2, riskWeight: 2 },
      { labelKg: 'Жөн гана ыйлайт же кыйкырат', labelRu: 'Просто плачет или кричит', points: 2, riskWeight: 2 }
    ]
  },
  {
    id: 3,
    questionKg: 'Балаңыздын активдүү сүйлөөсү кандай деңгээлде?',
    questionRu: 'Каков уровень активной речи ребенка?',
    category: 'speech',
    ageRange: '2 - 7 жаш',
    options: [
      { labelKg: 'Толук сүйлөм менен эркин сүйлөйт (бир нече тыбыш гана ката)', labelRu: 'Говорит развернутыми фразами (только отдельные звуки нарушены)', points: 0, riskWeight: 0 },
      { labelKg: '2-3 сөздөн турган жөнөкөй сөз айкаштары («Мама бер», «Суу ичем»)', labelRu: 'Простые фразы из 2-3 слов («Мама дай», «Хочу пить»)', points: 1, riskWeight: 1 },
      { labelKg: 'Жекече гана сөздөр же муундар («ма», «па», «би-би»)', labelRu: 'Только отдельные слова или лепетные слоги', points: 2, riskWeight: 2 },
      { labelKg: 'Такыр сүйлөбөйт (үн же ымдоо гана)', labelRu: 'Полное отсутствие речи (только звуки/жесты)', points: 3, riskWeight: 3 }
    ]
  },
  {
    id: 4,
    questionKg: 'Катуу үндөргө, кийимдин этикеткасына же чач кыркууга реакциясы кандай?',
    questionRu: 'Как ребенок реагирует на громкие звуки, ярлычки на одежде или стрижку?',
    category: 'sensory',
    ageRange: '1.5 - 7 жаш',
    options: [
      { labelKg: 'Кадимкидей, эч кандай коркуу же каршылык жок', labelRu: 'Спокойно, без выраженного дискомфорта', points: 0, riskWeight: 0 },
      { labelKg: 'Кулагын басат, ыйлайт, чач кырктырбайт же кийимди чечет', labelRu: 'Закрывает уши, плачет при звуках пылесоса/стрижке', points: 2, riskWeight: 2 },
      { labelKg: 'Кээ бир тамактардын текстурасын такыр жебейт', labelRu: 'Крайне избирателен в еде (только определенная текстура)', points: 1, riskWeight: 1 }
    ]
  },
  {
    id: 5,
    questionKg: 'Балаңыздын кыймыл-аракети жана координациясы кандай?',
    questionRu: 'Какова координация движений и моторная активность ребенка?',
    category: 'motor',
    ageRange: '2 - 7 жаш',
    options: [
      { labelKg: 'Жакшы чуркайт, секирет, тепкичтен өзү чыгат', labelRu: 'Уверенно бегает, прыгает, ходит по лестнице', points: 0, riskWeight: 0 },
      { labelKg: 'Бат-баттан чалынып жыгылат, өтө шайдоот/эпсиз', labelRu: 'Часто спотыкается, неловкий в движениях', points: 1, riskWeight: 1 },
      { labelKg: 'Буттун учу менен басат, же кыймыл-аракети чектелген', labelRu: 'Ходит на носочках или есть выраженная спастика/слабость', points: 2, riskWeight: 2 }
    ]
  }
];
